# Define lineages for the analysis.
lineages:
  - h3n2

# Define genes to translate from nucleotide to amino acid sequences. These names
# must match coding regions defined in the reference.
genes:
  - SigPep
  - HA1
  - HA2

# Define parameters for specific steps of the workflow by name.
refine:
  coalescent: const
  date_inference: marginal
  clock_rate: 0.00382
  clock_std_dev: 0.000764

ancestral:
  inference: joint

frequencies:
  narrow_bandwidth: 0.25
  proportion_wide: 0.0
  min_date: 1968-01-01
  max_date: 2012-01-01
  pivot_interval: 3

clades:
  sites: 145 155 156 158 159 189 193
  minimum_frequency: 0.1
